### ISSUE TITLE
Link to validation IDs change layout

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/validation.dhall#15]
Padding on the left is missing when clicking an ID anchor.

https://validation.openmls.tech/
![image](https://github.com/user-attachments/assets/9e7d4822-f7e6-4aeb-8dbd-091edbda7a44)

https://validation.openmls.tech/#valn0101
![image](https://github.com/user-attachments/assets/ac1b73a7-5dfe-45fb-b512-4b89abbb26db)

**Comment by keks** [comment]
I can't reproduce this, maybe this was a transient issue or already fixed. Can you try again?

**Comment by franziskuskiefer** [comment]
Hm. I can't reproduce either. Maybe some fluke. Closing
